codeit-6team/The-julge

- src/components/common/Input.tsx
unit 값에 따라 선택 적용
unit 부분을 조건부로 사용 시 padding-right 60, 사용 안할 시 padding-right 20이 적용됩니다.
> 🐛 fix: unit 값에 따라 선택 적용

- src/components/common/Button.tsx
Button 컴포넌트의 middle size 높이를 수정하였습니다.
figma의 리소스 (공통 컴포넌트) 정리에서는 middle size의 height가 37px로 되어있어 그대로 했는데 실제 사용 figma를 확인해보니 계속 38px로 되어있어 높이를 수정하였습니다.
공통 컴포넌트
실사용
Resolves: #39
> 🎨 style: middle size Button 컴포넌트 height 수정

- src/components/common/notification-modal/NotificationCard.tsx
- src/components/common/notification-modal/NotificationModal.tsx
- src/utils/formatWorkTime.ts
-  근무 시작 시간과 근무 진행 시간을 입력하면 근무 시작 시간 ~ 근무 종료 시간을 `"YYYY-MM-DD HH:mm~HH:mm"` 형식의 문자열로 반환하는 함수 **formatWorkTime**에 대해 예외 처리를 추가했습니다.
- UTC를 KST로 변환하는 과정이 2번 반복되는 문제를 해결했습니다.
- prop 명을 변경했습니다.
- **formatWorkTime** 함수에 잘못된 근무 시작 시간을 전달할 시에 'NaN-NaN-NaN NaN:NaN~NaN:NaN' 를 리턴하는 문제 발생
이런 문제 상황을 함수 내에서 확인하도록 코드를 추가하여, 잘못된 근무 시작 시간이 전달되면 `null`를 리턴하도록 수정했습니다.
- Date()에서 자동으로 kst로 변환이 되므로 9시간을 더해주는 코드를 삭제했습니다.
- `workHour` prop을 api 응답 데이터에 맞게 `workhour`로 변경했습니다.
- #50
> ✨ feat: formatWorkTime함수에 잘못된 시간이 전달되었을 경우에 대한 예외 처리 추가

- src/api/api.ts
- src/api/getAlerts.ts
- src/api/postToken.ts
- src/api/postUser.ts
- src/components/common/notification-modal/NotificationModal.tsx
- src/context/AuthContext.tsx
로그인 및 회원가입 로직을 구현했습니다.
추가로, 로그인 로직에 알림을 받아오는 기능이 포함되어 있어, 알림 관련 로직도 함께 구현되었습니다.
- api 관련
- 공통 Axios 인스턴스 설정 및  interceptor 설정 (Authorization 헤더 자동 주입) (`api/api.ts`)
- 로그인 API 호출 로직 작성 (`api/postToken.ts`)
- 회원가입 API 호출 로직 작성 (`api/postUser.ts`)
- 알림 API 호출 로직 작성 (`api/getAlerts.ts`)
- 로그인 / 회원가입 로직
- 로그인 및 로그아웃 함수 AuthContext 내에서 구현 (`context/AuthContext.tsx`)
- 로그인 성공 시 localstorage에 accessToken 저장 (`context/AuthContext.tsx`)
- 로그인 시 알림 불러오도록 구현 (`context/AuthContext.tsx`)
- ❗ 수정사항
- 알림 response에 따라 알림 타입 수정 (`common/NotificationModal` , `context/AuthContext.tsx` )
내용이 많아서 아래에 추가 및 수정된 주요 파일들에 대한 설명을 좀 덧붙이겠습니다~!
```ts
import axios from 'axios';
const api = axios.create({
baseURL: 'https://bootcamp-api.codeit.kr/api/15-6/the-julge', // 공통 prefix
headers: {
'Content-Type': …
```
> ✨ feat: 로그인 및 회원가입 로직 구현

- src/components/common/Dropdown.tsx
드롭다운 컴포넌트의 z-index 추가
z-index 30을 추가하여 인풋 부분에 가려지는 현상을 수정
- #85
> 🐛 fix: Dropdown 컴포넌트의 z-index 추가

- src/api/applicationApi.ts
- src/api/noticeApi.ts
application API type들을 정의했습니다.
Resolves: #68 
- status에 `'pending' | 'accepted' | 'rejected' | 'canceled'` 과 `'accepted' | 'rejected' | 'canceled'` 2가지 union type 이 있는데 현재는 그냥 객체 안에 적었습니다만 별개로 분리하는 게 좋을지 의견 구해봅니다
- alert에서 사용하는 application은 형태가 조금 달라 `applicationApi` 파일에 넣지 않고 그대로 `alertApi` 파일에 남겼는데 분리해서 파일에 넣는게 좋을까요?
> ✨ feat: application API 파일 생성 및 타입 정의

- src/api/shopApi.ts
shop API 함수들을 구현했습니다
- POST `/shops` 함수 구현
- GET `/shops/{shop_id}` 함수 구현
- PUT `/shops/{shop_id}` 함수 구현
Resolves: #77
테스트 결과 모두 정상 작동하긴 하는데 문제가 생긴다면 말씀해주세요!
> ✨ feat: shop API 함수 구현

- src/api/noticeApi.ts
- src/components/common/Post.tsx
- notice API 함수들을 구현했습니다.
- `noticeApi` 파일의 type들을 리팩토링하였습니다.
- `getNotices` : GET `/notices` 함수
- `getShopNotices` : GET `/shops/{shop_id}/notices` 함수
- `postShopNotice` : POST `/shops/{shop_id}/notices` 함수
- `getShopNotice`  : GET `/shops/{shop_id}/notices/{notice_id}` 함수
- `putShopNotice` : PUT `/shops/{shop_id}/notices/{notice_id}` 함수
Resolves: #76 
- Shop 이 붙은 API 함수들의 이름에서 Shop을 빼고 `getNotices` > `getTotalNotices` 이런 식으로 바꿀까 생각도 했는데 일단은 최대한 api url과 비슷하게 두었습니다.
- `putShopNotice`의 마감된 공고는 수정할 수 없습니다 빼고 일단 동작하는 것을 테스트 완료했습니다.
> ✨ feat: notice API 함수 구현 및 type 리팩토링

- src/components/layout/RegisterLayout.tsx
- src/pages/profile/ProfileForm.tsx
내 프로필 상세 페이지와 가게 정보 상세 페이지에서 등록 전의 레이아웃이 겹치므로 해당 레이아웃을 분리했습니다.
- type은 profile, store, application, notice로 주어집니다.
- profile: 내 프로필 등록 전
- store: 내 가게 등록 전
- application: 알바 지원 전
- notice: 공고 올리기 전
- #117 
- 주영님이 구현해두신 버튼의 size prop으로 버튼의 크기를 조절할 수 있다는 걸 알고 있습니다. 
다만, 현재 모바일에서는 버튼의 size가 medium 이고 태블릿 이상부터는 버튼의 size가 large입니다.
화면의 크기에 따라 버튼의 size를 다르게 주려면 window.innerwidth를 사용해야 하는데, 이것보단 그냥 tailwind의 반응형 속성을 활용하는게 더 편할 것 같아서, size는 medium으로 두고, large 사이즈는 클래스로 구현했습니다.
> ✨ feat: RegisterLayout 컴포넌트 구현

- src/components/common/Post.tsx
Post 컴포넌트 className Props 추가 및 고정 width 수정
className props 추가와 전체적으로 고정 width를 다 full로 변경했습니다.
- #125
> 🐛 fix: Post 컴포넌트 className Props 추가 및 고정 width 수정

- src/components/common/notification-modal/NotificationCard.tsx
- src/components/common/notification-modal/NotificationModal.tsx
알림 읽음 기능을 구현했습니다.
알림을 클릭 시 해당 공고 페이지로 이동하며, 해당 알림은 읽음 처리되어 알림 모달에서 제외됩니다.
- #122 
현재 공고 페이지가 구현되지 않아서 테스트가 어렵습니다. 잘 동작할지 모르겠어서 추후 수정할 부분이 생기면 수정하겠습니다.
> ✨ feat: 알림 읽음 처리 구현

- src/pages/store/StoreForm.tsx
- 공고 등록 (StoreForm) 페이지 컴포넌트를 구현했습니다.
- 공고 등록(post) 부분을 구현했습니다. **편집 기능은 없습니다.**
- 시작 일시는 input 기본 type `datetime-local`을 사용했습니다.
- X 버튼 클릭시 가게 정보 상세 페이지로 돌아갑니다.
Resolves: #88
https://github.com/user-attachments/assets/728a973e-2213-4559-8a72-a7593bc920f1
- `ProfileForm`을 복사해 와 매우 유사하게 구현했습니다.
- 제어/비제어 컴포넌트 문제인지 console에 error가 뜨기는 하나 동작 자체에는 문제가 없어 고치지는 않았습니다. (시도는 해봤는데 복잡해서 고치려고 한다면 조금 걸릴 듯 합니다)
> ✨ feat: 공고 등록 (StoreForm) 페이지 구현

- src/App.tsx
- src/components/common/Post.tsx
- src/pages/store/StoreForm.tsx
현재 공고 상세 페이지의 경로에 noticeId만 포함되어 있는데, shopId도 포함시켰습니다.
post 컴포넌트를 클릭 시 해당 공고 상세 페이지로 이동하도록 onClick속성 추가했습니다.
- 내 가게 공고 상세 (사장님) | /owner/post/{shopId}/{noticeId}
- 공고 상세 | /{shopId}/{noticeId}
- Post 클릭 시 해당 공고 상세 페이지로 이동
- #132 
공고 상세 페이지가 2개인데, 내 가게의 공고일 경우에 어떻게 내 가게 공고 상세 페이지로 이동시킬 지 고민을 했는데, /owner로 시작하는 경로는 내 가게에 대한 페이지들이므로, 
/owner로 시작하는 페이지에서 post를 클릭 시 내 가게 공고 상세 페이지로 이동하며, 
나머지 경우(공고 리스트 페이지)에서는 공고 상세 페이지로 이동하도록 했습니다.
> 🐛 fix: url 경로 수정 및 post 컴포넌트 수정

- src/api/noticeApi.ts
- src/components/common/PostLarge.tsx
공고 상세페이지에서 사용되는 PostLarge 컴포넌트를 만들었습니다.
- `Post` 컴포넌트와 유사합니다.
- `data` prop으로 `NoticeDetailItem` 형식의 데이터를 받아서 보여줍니다.
- **`children` prop으로 버튼**을 받아 위치시킵니다.
- `className` prop로 스타일을 지정할 수 있습니다.
- 너비를 지정하지 않았습니다.
Resolves: #133 
- 공고 설명이 없을 경우의 처리를 따로 하지는 않았습니다.
- 버튼의 스타일과 로직이 다양하여 어떻게 처리를 할까하다 Button을 children으로 받게 구현했습니다.
- 구현 이미지는 mockdata를 활용했습니다.
> ✨ feat: PostLarge 컴포넌트 구현

- src/pages/store/StorePost.tsx
사장님 공고 상세(StorePost) 페이지를 구현했습니다.
- 로그인 상태가 아니라면 (localStorage에 userId가 없으면) 로그인이 필요합니다 모달창을 띄웁니다. 로그인 페이지 `/login`로 보냅니다.
- 경로의 params에서 shopId/noticeId 가 존재하는 아이디가 아니라면 존재하는 공고가 아닙니다 모달창을 띄웁니다. 가게 페이지 `/owner/store`로 보냅니다.
Resolves: #113 
https://github.com/user-attachments/assets/a0f5d411-ca97-4176-9b9a-7964136483b7
- 공고 편집 경로가 존재하지 않아 공고 편집하기 버튼은 동작하지 않습니다.
> ✨ feat: 사장님 공고 상세(StorePost) 페이지 컴포넌트 구현

- src/components/common/notification-modal/NotificationCard.tsx
- src/components/common/notification-modal/NotificationModal.tsx
- src/components/layout/Navbar.tsx
- src/context/AuthContext.tsx
알림 읽음 관련 기능 수정
div 태그 link로 수정
- 알림 기능이 정상동작하지 않는 문제가 있어 관련 로직 수정했습니다.
- div를 link로 수정한뒤 알림 읽음 처리는 onclick에 남겨뒀습니다.
- #147
> 🐛 fix: 알림 읽음 기능 수정 및 div 태그를 link로 수정

- src/components/common/Post.tsx
Post 컴포넌트 내에서 클릭시 페이지 이동하는 기능이 있으므로 div를 link로 변경하였습니다.
최상위 div태그를 Link로 변경하고, 경로 이동 관련 기능은 to속성에 추가하였습니다.
최근 본 공고 저장 기능은 onClick에 유지시켰습니다,
- #145
> 🐛 fix: Post 컴포넌트 내 div 태그를 link태그로 수정

- src/components/common/table/Table.tsx
- src/components/common/table/TableButtons.tsx
Table의 Modal에서 일부 요소가 배경에 가려지지 않는 스타일 오류를 수정하였습니다.
- 모달을 `TableButtons` > `Table`으로 옮겼습니다.
Resolves: #142 
- 버그 발생 원인은 모달이 `Table` 아래의 `TableButtons` 컴포넌트에서 모달을 로드하여 부모 요소의 쌓임 맥락을 넘을 수 없어서 입니다.
> 🐛 fix: Table Modal 오류 수정

- src/pages/notice/NoticeList.tsx
검색 페이지 내에서 푸터가 뜨는 스타일 오류 수정
상위 태그에 flex를 적용하여, 가운데 태그를 늘렸습니다.
- #153 
수정 전
수정 후
> 🐛 fix: 검색 페이지 내에서 푸터가 뜨는 스타일 오류 수정

- README.md
Readme 작성했습니다.
Readme 간단한 틀만 잡아두었습니다~
배포 링크는 아직 준비되지 않아 추후에 추가하겠습니다~
추가하실 부분 / 삭제하실 부분 / 수정하실 부분 있으시면 편하게 해당 브랜치 내에서 커밋하셔도 됩니다~
- #130
> 📝 docs: Readme 파일 생성
